### ISSUE TITLE
There are a lot of bugs, do you really run by yourself

### ISSUE THREAD

**Issue by wenqiwenqi1** [ETHRuiGong/DLOW#3]

**Comment by ETHRuiGong** [comment]
Hi,

Sorry for that. Could you please check whether you could run the code now?

Thanks a lot!

Best Regards,
Rui

**Comment by wenqiwenqi1** [comment]
我用这行命令跑：python train.py --dataroot ./facedata --name projectname --model cycle_gan --checkpoints_dir ./checkpoints --gpu_ids 0 --lambda_identity 0 --lambda_GA 0 --lambda_GB 0 --display_id -1 --save_epoch_freq 10

先报networks.py里ModuleNotFoundError: No module named 'modules'，这个容易解决我加上了model.modules
然后又继续报错：
 File "D:\pytorch-CycleGAN-and-pix2pix\models\base_model.py", line 60, in get_current_losses
    errors_ret[name] = getattr(self, 'loss_' + name)
AttributeError: 'CycleGANModel' object has no attribute 'loss_D_A_Classification0'
您修改完后还是报这个错，我只有把这句try except起来才能跑起来训练，请问是什么原因呢

**Comment by wenqiwenqi1** [comment]
Your name is like a Chinese name，if not i will use english and apologize. At the same time I have another question, is it necessary to rename the file '110_net_G_B.pth' to '110_net_G.pth' during testing?

**Comment by ETHRuiGong** [comment]
> Your name is like a Chinese name，if not i will use english and apologize. At the same time I have another question, is it necessary to rename the file '110_net_G_B.pth' to '110_net_G.pth' during testing?

Yes, like in the test_model.py, you need 'G', 'DeConv' to run test.

**Comment by ETHRuiGong** [comment]
> 我用这行命令跑：python train.py --dataroot ./facedata --name projectname --model cycle_gan --checkpoints_dir ./checkpoints --gpu_ids 0 --lambda_identity 0 --lambda_GA 0 --lambda_GB 0 --display_id -1 --save_epoch_freq 10
> 
> 先报networks.py里ModuleNotFoundError: No module named 'modules'，这个容易解决我加上了model.modules
> 然后又继续报错：
> File "D:\pytorch-CycleGAN-and-pix2pix\models\base_model.py", line 60, in get_current_losses
> errors_ret[name] = getattr(self, 'loss_' + name)
> AttributeError: 'CycleGANModel' object has no attribute 'loss_D_A_Classification0'
> 您修改完后还是报这个错，我只有把这句try except起来才能跑起来训练，请问是什么原因呢

The first question is due to the version of python... If I use python2.7, it runs correctly;

The second question is due to that I miss some versions of my code. So I updated train.py just now, you can check it.

**Comment by wenqiwenqi1** [comment]
> > 我用这行命令跑：python train.py --dataroot ./facedata --name projectname --model cycle_gan --checkpoints_dir ./checkpoints --gpu_ids 0 --lambda_identity 0 --lambda_GA 0 --lambda_GB 0 --display_id -1 --save_epoch_freq 10
> > 先报networks.py里ModuleNotFoundError: No module named 'modules'，这个容易解决我加上了model.modules
> > 然后又继续报错：
> > File "D:\pytorch-CycleGAN-and-pix2pix\models\base_model.py", line 60, in get_current_losses
> > errors_ret[name] = getattr(self, 'loss_' + name)
> > AttributeError: 'CycleGANModel' object has no attribute 'loss_D_A_Classification0'
> > 您修改完后还是报这个错，我只有把这句try except起来才能跑起来训练，请问是什么原因呢
> 
> The first question is due to the version of python... If I use python2.7, it runs correctly;
> 
> The second question is due to that I miss some versions of my code. So I updated train.py just now, you can check it.

thanks.i'll try it later
