### ISSUE TITLE
Loss in the codes different from that in the paper?

### ISSUE THREAD

**Issue by lipingtang17** [ETHRuiGong/DLOW#4]
Dear Rui,

Thanks you for sharing your codes. But I think that you're using a different loss from your paper to update the parameters of generators and discriminators. I think the cycle consistency loss is the same, but you're using a different adversarial loss in your codes. In your paper, the output of a generator will be forwarded to both discriminators. But you update G_A only using the output of D_A(G_A(A)) and update G_B only using D_B(G_B(B)). And I think the loss used when updating parameters in the discriminator is different from the paper, too. 

Did I miss anything or misunderstand anything? 

I'd appreciate it if you could have a reply!

Liping

**Comment by ETHRuiGong** [comment]
Hi, Liping,

Thanks for your interest in our paper. When there are two target  domains available, the domain distance is weighted by the z and (1-z). When multiple target domains available, the domain distance is weighted by the element of the domainness vector [z1, z2,...z5]. In our code, the domain distance is weighted by the element of the domainness vector [z1, z2,...z5]. For more details, you can refer to the paper section 3.6 in main paper and Figure 9 in supplementary.

Best Regards,
Rui
