### ISSUE TITLE
about loss and dataset question

### ISSUE THREAD

**Issue by cymizer** [ETHRuiGong/DLOW#5]
Thanks you for sharing your codes.  I still have some question after studying your paper and codes. 
1.how do you set up the datasets placing ? Could you give an example on your code ?
2. I confuse about loss discriminator backward. what is the difference for D_A and D_B setting?
I'd appreciate it if you could have a reply

**Comment by ETHRuiGong** [comment]
Hello,

For the first question, actually, I could not really get the meaning of "dataset placing". We follow the dataset placing habit as done is CycleGAN.

For the second question, D_A and D_B represent the two directions: S->T and T->S. The network structure is the same. I am not sure whether your "setting" means "structure"?

Best Regards,
Rui
