### ISSUE TITLE
which one is the DLOW model and the required enviroment

### ISSUE THREAD

**Issue by JunMa11** [ETHRuiGong/DLOW#7]
Hi @ETHRuiGong ,

Thanks for sharing the great work.

1. Could you please tell me which one is the DLOW model?

![image](https://user-images.githubusercontent.com/19947331/131095636-514ddfac-52a2-4bc9-8205-69d85b113734.png)

2. Could you list the required enviroment?
e.g., the version of python, torch, cuda...

**Comment by JunMa11** [comment]
3. How to reproduce the results in Fig. 7

![1630054595(1)](https://user-images.githubusercontent.com/19947331/131101476-7d8264bc-2e75-4784-a941-9c36ebb6ab44.png)

Looking forward to your reply:)

**Comment by ETHRuiGong** [comment]
Hi, the GTA-->Cityscapes experiment is the single-target domain experiment. If you need the code for single target domain, please write the e-mail to gongr@vision.ee.ethz.ch. 

For the environment, I follow the environment of the CycleGAN (pytorch 0.4.0).
