### ISSUE TITLE
beta distribution of variable z

### ISSUE THREAD

**Issue by dohoseok** [ETHRuiGong/DLOW#8]
In implementation paragraph of your paper chapter 3.4, it is written that the domainness variable z obey the beta distribution.
Is it implemented in your code? I found only np.random.rand in cycle_gan_model.py code.

**Comment by ETHRuiGong** [comment]
Hi, as described in the paper, the beta distribution is used in the single target domain setting. If you need the code for single target domain, please write an e-mail to gongr@vision.ee.ethz.ch.
